apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-kubernetes-example
spec:
  selector:
    matchLabels:
      app: spring-kubernetes-example
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-kubernetes-example
    spec:
      containers:
       - name: spring-kubernetes-example
         image: spring-boot-kubernetes-k1
         imagePullPolicy: IfNotPresent
         ports:
          - containerPort: 8080 # port that container is running on in the cluster
