apiVersion: v1
kind: Service
metadata:
  name: spring-kubernetes-example-service
spec:
  selector:
    app: spring-kubernetes-service
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
